version: "3.7"
services:
  api:
    build:
      context: ""
      dockerfile: Docker/Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/usr/mainsrc/app
    depends_on:
      - postgress-db
    ports:
      - 4000:4000

  postgress-db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_MULTIPLE_DATABASES}
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./Docker/pg-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgress-db
    ports:
      - 4040:8080

volumes:
  postgres:
